"""Add acceptance_type

Revision ID: 1a2a95b712f0
Revises: f650e39cdd58
Create Date: 2026-09-01 21:26:52.457239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2a95b712f0'
down_revision: Union[str, Sequence[str], None] = 'f650e39cdd58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_receipts', sa.Column('acceptance_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_receipts', 'acceptance_type')
    # ### end Alembic commands ###
