"""Initial sqlite migration

Revision ID: f650e39cdd58
Revises: 
Create Date: 2026-08-27 16:31:38.553643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f650e39cdd58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firms_id'), 'firms', ['id'], unique=False)
    op.create_index(op.f('ix_firms_is_active'), 'firms', ['is_active'], unique=False)
    op.create_index(op.f('ix_firms_name'), 'firms', ['name'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('manager_name', sa.String(length=255), nullable=True),
    sa.Column('manager_email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_active'), 'plants', ['active'], unique=False)
    op.create_index(op.f('ix_plants_code'), 'plants', ['code'], unique=True)
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_plant_id'), 'users', ['plant_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('invoice_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('item_quantity_ordered', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('current_stage_entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_owner_role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'po_number', 'invoice_number', name='uix_plant_po_invoice')
    )
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_current_owner_role'), 'invoices', ['current_owner_role'], unique=False)
    op.create_index(op.f('ix_invoices_current_stage'), 'invoices', ['current_stage'], unique=False)
    op.create_index(op.f('ix_invoices_current_stage_entered_at'), 'invoices', ['current_stage_entered_at'], unique=False)
    op.create_index(op.f('ix_invoices_firm_id'), 'invoices', ['firm_id'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_plant_id'), 'invoices', ['plant_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('related_round_type', sa.String(length=50), nullable=True),
    sa.Column('related_round_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_by_user_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('response_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_id'), 'followups', ['id'], unique=False)
    op.create_index(op.f('ix_followups_invoice_id'), 'followups', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_followups_sent_at'), 'followups', ['sent_at'], unique=False)
    op.create_index(op.f('ix_followups_sent_by_user_id'), 'followups', ['sent_by_user_id'], unique=False)
    op.create_table('invoice_passing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('passed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('passed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('passed_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('frm_number', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_passing_id'), 'invoice_passing', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_passing_invoice_id'), 'invoice_passing', ['invoice_id'], unique=True)
    op.create_index(op.f('ix_invoice_passing_payment_date'), 'invoice_passing', ['payment_date'], unique=False)
    op.create_table('invoice_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('revised_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('revised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revised_by_user_id', sa.Integer(), nullable=True),
    sa.Column('revision_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revised_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_revisions_id'), 'invoice_revisions', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_revisions_invoice_id'), 'invoice_revisions', ['invoice_id'], unique=False)
    op.create_table('material_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('received_by_user_id', sa.Integer(), nullable=True),
    sa.Column('receipt_notes', sa.Text(), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('inspection_notes', sa.Text(), nullable=True),
    sa.Column('pbg_acceptance_date', sa.Date(), nullable=True),
    sa.Column('contract_agreement_date', sa.Date(), nullable=True),
    sa.Column('acknowledgement_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_receipts_id'), 'material_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_material_receipts_invoice_id'), 'material_receipts', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_material_receipts_receipt_date'), 'material_receipts', ['receipt_date'], unique=False)
    op.create_table('observation_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raised_by_user_id', sa.Integer(), nullable=True),
    sa.Column('observation_title', sa.String(length=255), nullable=True),
    sa.Column('observation_details', sa.Text(), nullable=True),
    sa.Column('target', sa.String(length=50), nullable=True),
    sa.Column('intimated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intimated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expected_reply_date', sa.Date(), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_notes', sa.Text(), nullable=True),
    sa.Column('resubmitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resubmitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['intimated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resubmitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'round_number', name='uix_invoice_round_observation')
    )
    op.create_index(op.f('ix_observation_rounds_id'), 'observation_rounds', ['id'], unique=False)
    op.create_index(op.f('ix_observation_rounds_invoice_id'), 'observation_rounds', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_observation_rounds_resolved_at'), 'observation_rounds', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_observation_rounds_target'), 'observation_rounds', ['target'], unique=False)
    op.create_table('replacement_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('intimated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intimated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expected_reply_date', sa.Date(), nullable=True),
    sa.Column('intimation_notes', sa.Text(), nullable=True),
    sa.Column('firm_response', sa.String(length=20), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replacement_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replacement_quantity', sa.Integer(), nullable=True),
    sa.Column('replacement_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['intimated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'round_number', name='uix_invoice_round_replacement')
    )
    op.create_index(op.f('ix_replacement_rounds_firm_response'), 'replacement_rounds', ['firm_response'], unique=False)
    op.create_index(op.f('ix_replacement_rounds_id'), 'replacement_rounds', ['id'], unique=False)
    op.create_index(op.f('ix_replacement_rounds_invoice_id'), 'replacement_rounds', ['invoice_id'], unique=False)
    op.create_table('stage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('acted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delay_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['acted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_events_acted_by_user_id'), 'stage_events', ['acted_by_user_id'], unique=False)
    op.create_index(op.f('ix_stage_events_delay_type'), 'stage_events', ['delay_type'], unique=False)
    op.create_index(op.f('ix_stage_events_exited_at'), 'stage_events', ['exited_at'], unique=False)
    op.create_index(op.f('ix_stage_events_id'), 'stage_events', ['id'], unique=False)
    op.create_index(op.f('ix_stage_events_invoice_id'), 'stage_events', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_stage_events_stage_name'), 'stage_events', ['stage_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_events_stage_name'), table_name='stage_events')
    op.drop_index(op.f('ix_stage_events_invoice_id'), table_name='stage_events')
    op.drop_index(op.f('ix_stage_events_id'), table_name='stage_events')
    op.drop_index(op.f('ix_stage_events_exited_at'), table_name='stage_events')
    op.drop_index(op.f('ix_stage_events_delay_type'), table_name='stage_events')
    op.drop_index(op.f('ix_stage_events_acted_by_user_id'), table_name='stage_events')
    op.drop_table('stage_events')
    op.drop_index(op.f('ix_replacement_rounds_invoice_id'), table_name='replacement_rounds')
    op.drop_index(op.f('ix_replacement_rounds_id'), table_name='replacement_rounds')
    op.drop_index(op.f('ix_replacement_rounds_firm_response'), table_name='replacement_rounds')
    op.drop_table('replacement_rounds')
    op.drop_index(op.f('ix_observation_rounds_target'), table_name='observation_rounds')
    op.drop_index(op.f('ix_observation_rounds_resolved_at'), table_name='observation_rounds')
    op.drop_index(op.f('ix_observation_rounds_invoice_id'), table_name='observation_rounds')
    op.drop_index(op.f('ix_observation_rounds_id'), table_name='observation_rounds')
    op.drop_table('observation_rounds')
    op.drop_index(op.f('ix_material_receipts_receipt_date'), table_name='material_receipts')
    op.drop_index(op.f('ix_material_receipts_invoice_id'), table_name='material_receipts')
    op.drop_index(op.f('ix_material_receipts_id'), table_name='material_receipts')
    op.drop_table('material_receipts')
    op.drop_index(op.f('ix_invoice_revisions_invoice_id'), table_name='invoice_revisions')
    op.drop_index(op.f('ix_invoice_revisions_id'), table_name='invoice_revisions')
    op.drop_table('invoice_revisions')
    op.drop_index(op.f('ix_invoice_passing_payment_date'), table_name='invoice_passing')
    op.drop_index(op.f('ix_invoice_passing_invoice_id'), table_name='invoice_passing')
    op.drop_index(op.f('ix_invoice_passing_id'), table_name='invoice_passing')
    op.drop_table('invoice_passing')
    op.drop_index(op.f('ix_followups_sent_by_user_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_sent_at'), table_name='followups')
    op.drop_index(op.f('ix_followups_invoice_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_plant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_firm_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_current_stage_entered_at'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_current_stage'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_current_owner_role'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_plant_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_index(op.f('ix_plants_code'), table_name='plants')
    op.drop_index(op.f('ix_plants_active'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_firms_name'), table_name='firms')
    op.drop_index(op.f('ix_firms_is_active'), table_name='firms')
    op.drop_index(op.f('ix_firms_id'), table_name='firms')
    op.drop_table('firms')
    # ### end Alembic commands ###
